kind: Deployment
apiVersion: apps/v1
metadata:
  name: up-running-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: up-running-react
  template:
    metadata:
      labels:
        app: up-running-react
    spec:
      containers:
        - name: up-running-react
          image: mubo9/up-running-react
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---      
kind: Service
apiVersion: v1
metadata:
  name: up-running-react
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: up-running-react