name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: env 
      run: TAG=$(date +%s); echo "TAG=${TAG}" >> $GITHUB_ENV
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run:  |
        echo tag = ${env.TAG}
        docker build . --file Dockerfile --tag mubo9/up-running-react:${env.TAG}
   
    - name: Build & Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          mubo9/up-running-react:${{TAG}}  
